### ISSUE TITLE
Fix DAO filtering consistency

### ISSUE THREAD

**Issue by jacksonic** [foam-framework/foam2#102]
Make LimitedDAO, SkipDAO, etc. match the behaviour of FilteredDAO when object updates don't pass the test.

Also examine the role of the Sinks: PredicatedSink, LimitedSink, etc. Since listen() uses these to filter in the same way. removeAll() may make some assumptions about how remove() is filtered that are not compatible with this change. Likely there are multiple roles that require separate sink behaviours (select() assumes a clean slate for its sink output, for example, so doesn't need this put/remove swapping).
# Background

Currently FilteredDAO has event filter that ensure that objects which previously passed the test, but now fail, are removed from the listener so subscribers build an accurate picture of what the "filtered" state of the DAO should look like. If the listener is building an actual DAO, it will contain exactly the set of items that match the filter.

Puts that do not match are changed to Remove
Removes are never filtered

Ex:

```
- DAO: [ A{4}, B{3} ]
- filteredDAO( "< 5" ): [ A{4}, B{3} ]
DAO.put( B{6} ) // B no longer matches the filter
//put(B) event to filteredDAO, changes it to remove(B) event
- DAO: [ A{4}, B{6} ]
- filteredDAO( "< 5" ): [ A{4} ]
```

**Comment by adamvy-google** [comment]
I'm not sure LimitedDAO/SkipDAO should limit or skip the number of events coming through.

In FOAM1, dao.listen() purposefully ignored the limit/skip

**Comment by jacksonic** [comment]
Sounds like we can group 'transactional' features conceptually and in the docs. Things like skip, limit (and sink.eof) only apply to operations like select() with a defined start and end.
