### ISSUE TITLE
Indentation Lost when saving Nanos Scripts

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#1039]
Go to the Nanos Admin / Scripts menu and create a script which contains indented code.

Ex.

if ( true ) {
  print("true");
}

When the script is saved, it comes back as:

if ( true ) {
print("true");
}

Which makes it difficult to maintain well structured scripts.

Assigned to: @hchoura

**Comment by hchoura** [comment]
https://github.com/foam-framework/foam2/pull/1087
