### ISSUE TITLE
Support select() in ContextualizingDAO, optionally

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam2#112]
Requesting support for select() in ContextualizingDAO.  Of course it should be optional. 

We regularly use the results of a TableView selection or DAOList selection and are continually tripped up by forgetting to call 'find()' on the selection to set the context.  

Thanks
Joel

**Comment by kgrgreer** [comment]
In heroes/CitationView we have a delete button on the DAOList view which
needs access to the DAO the delete the row, but it gets it from the
CitationView, not the row data. Would this same technique work for you,
thus avoiding the need for your objects to have Contexts?  If not, can you
explain what you want to do with your objects that requires them to have a
context while in a TableView or DAOList?

Thanks

**Comment by jlhughes** [comment]
Other issues were cause us to blame context setup and now that we have things 'working', this is no longer required.
