### ISSUE TITLE
MDAO idIndex cleanup

### ISSUE THREAD

**Issue by adamvy-google** [foam-framework/foam2#132]
This really shouldn't happen.  If were missing some feature from ID support lets file a ticket for that rather than monkey-patch classes on the fly.

Relevant line:  https://github.com/foam-framework/foam2-experimental/blob/master/src/foam/dao/MDAO.js#L79

@kgrgreer

**Comment by adamvy-google** [comment]
Offending commit: a736c585913938eb75c77a0f97abce6a621bebed

**Comment by kgrgreer** [comment]
Indices are composites (chains), so I should be able to just ask the system to build an Index for the ID and set it to be my delegate without me having to know if it's a multi-part ID or a single-part.

**Comment by jacksonic** [comment]
This predates IDSupport, IIRC, and I'm looking at it now

**Comment by jacksonic** [comment]
Original title: MDAO sets this.of$cls.ids = ['id'];  It shouldn't mutate the class.

**Comment by jacksonic** [comment]
This also includes the final refactoring to change the names of some of the index setting methods.

**Comment by jacksonic** [comment]
Related tasks broken out: #134, #135
