### ISSUE TITLE
Getting the DAO for a relationship on the java side does not work. 

### ISSUE THREAD

**Issue by shreymahendru** [foam-framework/foam2#1373]
Ex: ``user.getPartners()``
This returns DAO which has the property ``isDelegateSet_ = true`` 
but the delegate is actually ``null`` and hence throws a NullPointerException in ProxyDAO. when a ``select`` is done on that DAO.

In order to make this work you have to do the following:
 ``user.fclone()`` 
 ``user.setX(x)`` 
This returns a correct DAO and the ``select`` works as intended.

**Comment by kgrgreer** [comment]
We should make the getParners() method take a context, as that's less obtrusive/expensive than having to clone.

**Comment by shreymahendru** [comment]
``user.fclone()`` is the essential part for making this work. 
Simply setting X on the user object, doesn't work (Given the x is being set, and we don't block updates on frozen objects Yet).

**Comment by kgrgreer** [comment]
I didn't mean to call setX(), I meant change the signature of the method to getPartners(X x) and have it use the supplied 'x' rather than calling getX(). The problem with setX() is that it's a hidden part of the API. This would make it explicit.

**Comment by adamvy** [comment]
We can add X to getPartners(), but it would also be worth figuring out where/how you got a user object that doesn't have the proper context.

Before you do fclone/setX(), does user.getX().get("userDAO") return you a DAO or null?

**Comment by kgrgreer** [comment]
Why does the user need a Context? Data objects having contexts has caused us a lot of memory issues in the past (in XHome). Also, it isn't a visible part of the API so the user might not know to set it. If it just doesn't work, then they can catch it, but the worse case is that it does work but they inadvertently gain somebody else's permissions.

**Comment by adamvy** [comment]
Well the user shouldn't ever have to set the context manually, it should be applied by a contextualizing DAO.  The context is not something we ever (or ever should) store for an object, its not serialized, but we should also explicitly strip it on put into an DAO.

Making data objects not have contexts seems reasonable but its a pretty big departure from what we currently have where all objects are FObjects which implies ContextAware.  Being more context oriented for some of these purposes would certainly save some resources and might be more clear.
