### ISSUE TITLE
Nested slots in U2 elements cause lots of "Must output/load before unloading" errors.

### ISSUE THREAD

**Issue by adamvy-google** [foam-framework/foam2#138]
It looks like if you have a slot which returns another slot which returns elements, the inner slots elements are not getting cleaned up, or at least not being removed from "childNodes" somewhere.  Because they the longer I let that inner slot change, the more warnings I get when I destory the parent node.

**Comment by adamvy-google** [comment]
@kgrgreer 

I can provide a demo/repro case if you want it

**Comment by kgrgreer** [comment]
@adamvy Do you have an example I can test against?

**Comment by adamvy-google** [comment]
I think I figured out the cause.

If you remove an element with .remove(), we don't actually update the parent's childNodes[] set, so the parentNode retains a reference to the now unloaded element we tried to .remove()

**Comment by adamvy-google** [comment]
Fixed in fdbb7bb31e4677290c97d95019dca12f36a7313a
