### ISSUE TITLE
Implement AltIndex

### ISSUE THREAD

**Issue by jacksonic** [foam-framework/foam2#145]
AltIndex currently only works when used as the root index. Implement the rest of it so that it can add indexes when used as a tail index in a chain.

This will involve the ability to find all its instances and populate the new index in each one. This could be done a few ways:
a) keep a list of all instances (bad)
b) pass the root index to addIndex() , modify AltIndex.put() to check for and create missing subindexes, and call put() on the root for every item (probably bad)
c) pass the root index to addIndex() and add a method to call up through the index and do the work  on all matching instances (being worked on)

**Comment by kgrgreer** [comment]
Why doesn't AltIndex work when not a root?

**Comment by jacksonic** [comment]
To build a complete index it needs to find all its "sibling" instances (the other tails in the tree it belongs to, for instance) and build the index for them too.

**Comment by jacksonic** [comment]
Also, this same kind of ability to make structural changes would allow for indexes that can decorate, remove or swap themselves.

**Comment by jacksonic** [comment]
Work in progress: be1185a4d97ed076ec46e034c57499d9fb9a9cf7

**Comment by jacksonic** [comment]
This is now working.
Pending: benchmarks to measure performance, more in depth tests and general cleanup.

**Comment by jacksonic** [comment]
Removing feature requirement to modify index structure. AltIndex on AutoIndex3 still retains some of the changes to separate delegate factories from instance delegates.
