### ISSUE TITLE
Models that use `implements` aren't getting properties defined on them

### ISSUE THREAD

**Issue by TW80000** [foam-framework/foam2#1529]
## Context

The following is from the documentation in [Implements.js](https://github.com/foam-framework/foam2/blob/master/src/foam/core/Implements.js):

> Axiom for declaring intent to implement an interface.

> Since interfaces can also have implementations, it can also be used to provide mix-ins, which is a safe form of multiple-inheritance.

```JavaScript
foam.CLASS({
  name: 'SalaryI',
  properties: [ 'salary' ]
});

foam.CLASS({
  name: 'Employee',
  extends: 'Person',
  implements: [ 'SalaryI' ]
});
```

> Employee extends Person through regular inheritance, but the axioms from SalaryI are also added to the class. Any number of mix-ins/interfaces can be specified.

## Expected Behaviour

Based on the example I'd expect that if `User` implements `LastModifiedAware`, then it would get the `lastModified` property defined on it without having to define it on itself.

## Actual Behaviour

`User` still defines `lastModified` on itself, so I don't see the point of using the interface. I was assuming it was a tool for abstracting away the need to constantly redefine common properties on many different models.

## Current Workaround

The current workaround is to define whatever properties are needed on the model doing the implementing.

**Comment by kgrgreer** [comment]
Fixed in FOAM3.
