### ISSUE TITLE
Generate warnings if required imports are missing.

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#159]
Also, add support to specifying which imports are required.
Maybe also provide optional factory for providing default value.

**Comment by jacksonic** [comment]
Along the 'factory' lines, specifying alternatives (try this, then that, default to other) would be handy to declare.

**Comment by jacksonic** [comment]
Dynamically names imports/exports is another case to ponder: "This class will import anything that ends with DAO" or "detailViewSpec.*"

**Comment by kgrgreer** [comment]
Done. Add '?' if import not required. Ex.
'dao?',
'UserDAO? as dao'
