### ISSUE TITLE
Register mock classes for testing or dependency injection

### ISSUE THREAD

**Issue by jacksonic** [foam-framework/foam2#179]
Currently hacked in test/src/lib/dao.js, search for env.__context__.__cache__['foam.box.HTTPBox']

Registering, replacing or exporting to swap one class for another is needed for dependency injection in particular subcontexts.

**Comment by adamvy-google** [comment]
Pretty sure this is already supported.

this.__subContext__.register(MockClass, 'foam.box.HTTPBox');

**Comment by adamvy-google** [comment]
Re-opening because the hack in dao.js should be removed.

**Comment by jacksonic** [comment]
registerInCache_() asserts if it finds an existing class. This issue is intended to add support for re-registering, or add a declarative way to do it.

**Comment by adamvy-google** [comment]
Do we need to support re-registering?

Why not create a sub-context and override in that sub-context, rather than re-registering the same class in the same context.

**Comment by adamvy-google** [comment]
Hmm, it looks like KEvin's lazy loading fixes may have broken this

@kgrgreer

**Comment by adamvy-google** [comment]
Okay I fixed registerInClass_ to support overriding classes in a sub-context again.
