### ISSUE TITLE
Packages that don't begin with "foam" pollute the global namespace

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam2#195]
FOAM2 aims to introduce exactly one global: 'foam'. IMHO, using the framework without explicitly declaring global variables should also not introduce global variables. The current implementation introduces a global for the beginning of every package name.

E.g., `foam.CLASS({package: 'foo', name: 'Bar', ...});` and `foam.LIB({name: 'foo.bar', ...});` both introduce the global `foo'.

**Comment by bshepherdson** [comment]
This is not a bug, or at least not an accident.

This was discussed already, and the decision was that we, meaning FOAM itself, only add `foam`. If you, meaning a user, define classes in other packages, then those appear in the namespace. That isn't "pollution", it's defining things based on your own names. We want to avoid accidental collisions, hence the hygiene for the framework proper, but you can name your own classes however you like.

**Comment by mdittmer** [comment]
Alright. I'll mark this as a feature request. It is desirable to be able to ask FOAM to hide my models and provide the lookup interface to access them.

**Comment by kgrgreer** [comment]
Just put your packages under 'foam' if this is an issue for you. ie. foam.com.google.someapp.somepackage.
