### ISSUE TITLE
ArrayDAO and ArraySink should have matching property names

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam2#251]
It's annoying to remember which one has `.array` and which one has `.a`.

**Comment by adamvy** [comment]
You should never be accessing .array on ArrayDAO

**Comment by adamvy** [comment]
Or "rarely" i should say :)

**Comment by mdittmer** [comment]
True. I tend to do this in test code though. I would argue that the more
descriptive `array` should be adopted into `ArraySink`, not the other way
around.

**Comment by adamvy** [comment]
fine with me

**Comment by kgrgreer** [comment]
If changed, the previous value should be supported with a psedo-property which generates warnings in order to give users a chance to migrate without breaking their code, then we can remove the backwards compatible property later.
