### ISSUE TITLE
DatastoreDAO.selectNextBatch not implemented

### ISSUE THREAD

**Issue by jingt06** [foam-framework/foam2#271]
DatastoreDAO.selectNextBatch used [here](https://github.com/foam-framework/foam2/blob/422b6c6e24bdcefd4c01aedd0702316e4b26bc27/src/com/google/cloud/datastore/DatastoreDAO.js#L246), but not implemented.

**Comment by mdittmer** [comment]
Fixed in 8fb3bedc6b81003736510e191e61d11f36284cb6 and ef3b333d8126df99623d638c37d20276011a052f
