### ISSUE TITLE
JournalDAO tests currently failing

### ISSUE THREAD

**Issue by drish** [foam-framework/foam2#304]
Tests are currently failing because of the JournalDAO test below, it gets stuck on it.

```
JournalDAO records write operations:
(node:54190) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'isInstance' of undefined
```

cc @adamvy

**Comment by mdittmer** [comment]
@adamvy it looks like some `NullDAO` tests are also hanging (found by disabling `JournalDAO` tests and retrying).

**Comment by adamvy** [comment]
Fixed
