### ISSUE TITLE
TestRunner.java - Test and quotes

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam2#335]
1. Single quotes need to be replaced with double
foam2/java_src/static/foam/nanos/test/TestRunner.java:14: error: unclosed character literal
    DAO tests = (DAO) getX().get('TestDAO');

2. foam.nanos.test.Test class missing properties: name, code
foam2/java_src/static/foam/nanos/test/TestRunner.java:33: error: <identifier> expected
    test1.name = "Test 1";
foam2/java_src/static/foam/nanos/test/TestRunner.java:34: error: <identifier> expected
    test1.code = "System.out.println(\"I'm working\");";

3. main declaration missing return type and opening  #parenthesis
void main() {

**Comment by kgrgreer** [comment]
This was just psedo-code to help someone get started on it. Test should extend Script which has those properties.

**Comment by jlhughes** [comment]
TestRunner renamed to .txt.
