### ISSUE TITLE
Port/Document/Test EasyDAO and all DAO decorators that it uses.

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#36]
Finish porting EasyDAO to FOAM2 as well as all of the DAO decorators that it uses.
Create unit tests.
Create a DAO programming guide (for users of DAOs, not for implementers of new types of DAO)
Create sub-issues as necessary.

**Comment by jacksonic** [comment]
EasyDAO milestone sub-issues tracking remaining tasks
