### ISSUE TITLE
foam.util.compare() is broken

### ISSUE THREAD

**Issue by m-cheung** [foam-framework/foam2#366]
There are several observed instances where foam.util.compare will not return the expected value
For example:

1. Given `a = undefined` and `b = anything`
`foam.util.compare(a, b) => 1` and `foam.util.compare(b, a) => 1`

2. Given `a = null` and `b = anything`
`foam.util.compare(a, b) => 1` and `foam.util.compare(b, a) => 1`

3. Given `a = true` and `b = FObject` (This one is really weird...)
`foam.util.compare(a, b) => 0` and `foam.util.compare(b, a) => 1`

**Comment by m-cheung** [comment]
Here are some examples of cases that remain unresolved by #368. These really don't have an intuitive answer to them and design choices will likely need to be made. 

For all cases below, the current result is `foam.util.compare(a, b) == foam.util.compare(b, a) == 1`

1. `a = []` and `b = 1`
2. `a = []` and `b = null`
3. `a = ""` and `b = null`
4. `a = function() {}` and `b = null`
5. `a = function() {}` and `b = undefined`
...

The core idea behind the issue stems from the fact that the primitive types usually perform a type check (`typeOf(b) == typeOf(a)`) and returns 1 when the types are not the same. Thus, we get 1 no matter what order is specified when these elements are compared.

**Comment by m-cheung** [comment]
To resolve the remaining issues, precedence has been assigned to each type. 

In the first attempt, precedence was determined by alphabetically (with `foam.Object` and `foam.core.FObject` being placed last). As you can see in this [Travis build](https://travis-ci.org/foam-framework/foam2/builds/233686152), this breaks some of the tests concerning the DAO. The main issue stems from the fact that `undefined` is the first parameter in a call to `foam.util.compare` in `foam.mlang.predicate.Gt`

In the second attempt, precedence was given to `foam.Undefined` and `foam.Null`, with the rest remaining in the same order as above. However, as you can see in this [Travis build](https://travis-ci.org/foam-framework/foam2/jobs/233688892), a test with regards to Date was broken. The failing test is `expect(foam.util.compare(new Date(234324), null)).toEqual(1);`

Alternatively, all of the tests will pass if priority is given just to `foam.Undefined` while the rest remain in the initial order that was described.

@mdittmer has suggested that the second approach makes the most sense and it gives precedence to the "simplest" types. @kgrgreer I would appreciate any input you can give on this.

**Comment by mdittmer** [comment]
@m-cheung fixed this in #368
