### ISSUE TITLE
JDAO.java bug in removeAll()

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#484]
removeAll_() journals a remove-all operation but doesn't check the predicate or limit parameters. So, something like dao.limit(0).where(false).removeAll() would remove all data from the journal, whereas no data should actually be removed.
@drish

**Comment by drish** [comment]
on it

**Comment by kgrgreer** [comment]
MapDAO has the same problem.

**Comment by drish** [comment]
@kgrgreer can we close this issue ?
