### ISSUE TITLE
JSONParser breaks when spaces are not included

### ISSUE THREAD

**Issue by MarcRoopchand** [foam-framework/foam2#544]
JSONParser.parseString breaks while trying to parse the line below. 
{class:"foam.box.Message",attributes:{},object:{class:"foam.box.RPCMessage",name:"login",args:["asdf","adsf"]}}

The fix is to put a spaces after each comma or update the parser to parse no spaces
{class:"foam.box.Message", attributes:{}, object:{class:"foam.box.RPCMessage", name:"login", args:["asdf","adsf"]}}

@TanayParikh @kgrgreer suggested this be assigned to you

**Comment by TanayParikh** [comment]
Thanks, I'll take a look.
