### ISSUE TITLE
TableView doesn't Update

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#568]
In a Nanos app create a Test in the Test menu. Click the "run" button and notice that the row doesn't update. If you leave the screen then return, then you'll see the update. I added pub() calls to the ClientDAO, but that doesn't work because the TableView is using listen(). It's confusing to have two dao listening methods at the moment.

**Comment by adamvy** [comment]
Okay I've fixed this by not sending listen_ requests to the server, and instead using the regular AbstractDAO implementation and publishing events local listeners.

In the future I will look at actually supporting remote listeners on nanos.

**Comment by kgrgreer** [comment]
Thanks
