### ISSUE TITLE
Add listen() and pipe() support back to DAO's

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#58]
Need to add logic to topics?

**Comment by jacksonic** [comment]
Currently implemented as methods on AbstractDAO, as before, but now using subscriptions. A more general topic-to-method-call proxy shortcut on topics would simplify the logic there.

**Comment by jacksonic** [comment]
TODO: SkipDAO, LimitDAO, etc. need to be updated to have filtered pipe and listen if we're sticking with methods on DAO

**Comment by jacksonic** [comment]
Implemented and tests active
