### ISSUE TITLE
foam.u2.ChoiceView does not appear to work with a dao of choices

### ISSUE THREAD

**Issue by adamvy-google** [foam-framework/foam2#82]
The select call is incorrect, using Map.create({ f: .... });

It probably needs to be Map.create({ arg1: this.objToChoice, delegate: some_sort_of_sink });

Additionally, the postSet for DAO does not call .onDAOUpdate(), so even if the dao was set it never updates the choices.

**Comment by bshepherdson** [comment]
I can't claim to have tested it thoroughly, or at all.

I'll fix it.

**Comment by bshepherdson** [comment]
Fixed by 8541475aa.
