### ISSUE TITLE
ValidationDAODecorator and DAODecorator

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam2#860]
1. DAODecorator.remove 
`this.decorator.remove(x, self.dao, self.obj)` should be 
`this.decorator.remove(x, self.dao, obj)`

2. ValidationDAODecorator is missing remove() and find()
DAODecorator expects a implementation of DAODecorator to implement these methods, obviously.  
Are there facilities to check this or it's simply the implementer's responsibility?
So either DAODecorator can check that a method exists before calling or we add the required methods to ValidationDAODecorator.

**Comment by adamvy** [comment]
Joel Hughes <notifications@github.com> writes:

> 1 DAODecorator.remove
>  this.decorator.remove(x, self.dao, self.obj) should be
>  this.decorator.remove(x, self.dao, obj)
>
> 2 ValidationDAODecorator is missing remove() and find()

ValidationDAODecorator should be changed to extend AbstractDAODecorator
which provides sensible default implementations for all DAODecorator
methods.

**Comment by jlhughes** [comment]
Thanks Adam, I'll create a pull request with the fixes.
